#!/bin/sh

#****************************************************************************
#***
#***   Copyright (c) 1997 by Max Moroz and ABKGroup, UCLA VLSI CAD Laboratory,
#***    UCLA Computer Science Department, Los Angeles, CA 90095-1596 USA,
#***    and by the Regents of the University of California.
#***    All rights reserved.
#***
#***    No portion of this package may be used, copied, or transmitted for
#***    any purpose, including any research or commercial purpose,
#***    without the express written consent of Professor Andrew B. Kahng,
#***    UCLA Computer Science Department, 3713 Boelter Hall, Los Angeles,
#***    CA 90095-1596 USA.   Any copy made of this file must include this
#***    notice.    ABKGroup and the Regents of the University of California
#***    retain title to all copies of this file and/or its compiled
#***    derivatives.
#***
#*****************************************************************************/

DIFF=/usr/bin/diff
WC=/usr/bin/wc
PROG=./ShellPartTest

rm -f new.out
rm -f seeds.in seeds.out *.diff

#echo "------------  Running test 1..." >> new.out
#echo -n Running test 1...
rm -f err.log
rm -f run.log

"${PROG}1.exe" -f TESTS/faraday_9709.aux -pl 40000 >>run.log 2>>err.log

egrep "(aux|Resulting|iolati|search)" run.log >>new.out

egrep -v "(Created|sec|User|Platform|Memory us)" new.out >newout.notime
egrep -v "(Created|sec|User|Platform|Memory us)" expected.out >expectedout.notime
"$DIFF" newout.notime expectedout.notime >diffs.notime

echo " "
echo Differences from precomputed results
echo "  lines:  words:  bytes:    error log:"
"$WC" diffs.notime
