#!/bin/sh

DIFF=/usr/bin/diff
WC=/usr/bin/wc
RM=/bin/rm
PROG=./AnalytPlTest0.exe

echo "------------  Running test saurabh..." >new.out
printf "%s" "------------  Running test saurabh... "
"$PROG" -f TESTS/intel.aux -verb 2_2_2 >>new.out
echo Ok

egrep -i -v time new.out >new.out.notime
egrep -i -v time expected.out >expected.out.notime

"$DIFF" new.out.notime expected.out.notime >diffs.notime
echo Differences from precomputed results
echo "  lines:  words:  bytes:    error log:"
"$WC" diffs.notime

"$RM" -f new.out.notime expected.out.notime
